name: lite_server
description: Lite Http Server for Dart
version: 1.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  mime: ^1.0.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
