name: lite_server
description: Lite Http Server for Dart
version: 0.2.4
repository: https://github.com/GeceGibi/lite_server.git

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  mime: ^2.0.0

dev_dependencies:
  very_good_analysis: ^7.0.0

