name: lite_server
description: Lite Http Server for Dart
version: 0.2.3
repository: https://github.com/GeceGibi/lite_server.git

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  mime: ^1.0.5

dev_dependencies:
  very_good_analysis: ^6.0.0

